# Generated by Django 5.2.13 on 2026-04-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(db_index=True, max_length=255)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[("full", "Full"), ("incremental", "Incremental")],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("config_hash", models.CharField(blank=True, max_length=64)),
                ("total_findings", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ScanDelta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("removed", "Removed"),
                            ("modified", "Modified"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "change_category",
                    models.CharField(
                        choices=[
                            ("subdomain", "Subdomain"),
                            ("service", "Service"),
                            ("vulnerability", "Vulnerability"),
                            ("port", "Port"),
                            ("dns", "DNS"),
                            ("ssl", "SSL"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_identifier", models.CharField(max_length=500)),
                ("change_details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "previous_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_deltas",
                        to="scans.scansession",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deltas",
                        to="scans.scansession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
