# Generated by Django 5.2.13 on 2026-04-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0003_add_uuid_to_scansession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scansession",
            name="config_hash",
        ),
        migrations.RemoveField(
            model_name="scansession",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="scandelta",
            name="change_category",
            field=models.CharField(
                choices=[("domain_finding", "Domain Finding")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="scandelta",
            name="change_type",
            field=models.CharField(
                choices=[("new", "New"), ("removed", "Removed")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="scansession",
            name="scan_type",
            field=models.CharField(default="full", max_length=20),
        ),
        migrations.AlterField(
            model_name="scansession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
