# Generated by Django 5.2.13 on 2026-04-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0006_add_triggered_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scansession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
