# Generated by Django 5.2.16 on 2026-08-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0010_add_partial_scan_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="scansession",
            name="endpoints_blocked",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scansession",
            name="endpoints_probed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scansession",
            name="waf_vendor",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
