# Generated by Django 5.2.17 on 2026-09-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0013_scheduledscan"),
        ("workflow", "0028_add_github_secrets_to_workflows"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="scansession",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "running"]),
                    models.Q(("scan_type", "subscan"), _negated=True),
                ),
                fields=("domain",),
                name="uniq_active_scan_per_domain",
            ),
        ),
    ]
