# Generated by Django 5.2.16 on 2026-08-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="reachability",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
