# Generated by Django 5.2.17 on 2026-08-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_assets", "0002_url_reachability"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="technologies",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
