# Generated by Django 5.2.13 on 2026-04-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="retry_count",
        ),
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[("slack", "Slack"), ("teams", "Microsoft Teams")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="status",
            field=models.CharField(
                choices=[("sent", "Sent"), ("failed", "Failed")],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
