# Generated by Django 5.2.14 on 2026-05-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_slack_and_teams_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_webhook_url", models.TextField(blank=True, default="")),
                ("teams_webhook_url", models.TextField(blank=True, default="")),
                (
                    "severity_threshold",
                    models.CharField(
                        choices=[
                            ("critical", "Critical only"),
                            ("high", "High and above"),
                            ("medium", "Medium and above"),
                            ("low", "Low and above"),
                        ],
                        default="high",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification config",
            },
        ),
    ]
