# Generated by Django 5.2.17 on 2026-09-06 03:39

import apps.core.fields
from django.db import migrations

# Webhook URLs now encrypted at rest — re-save existing rows to encrypt any
# plaintext already stored (runs after the columns are altered).
_SECRET_FIELDS = ["slack_webhook_url", "teams_webhook_url"]


def encrypt_existing(apps, schema_editor):
    Model = apps.get_model("alerts", "NotificationConfig")
    for obj in Model.objects.all():
        obj.save(update_fields=_SECRET_FIELDS)


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_notification_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationconfig",
            name="slack_webhook_url",
            field=apps.core.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="notificationconfig",
            name="teams_webhook_url",
            field=apps.core.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.RunPython(encrypt_existing, migrations.RunPython.noop),
    ]
