# Generated by Django 5.2.13 on 2026-04-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0005_alter_workflowstep_tool_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowstep",
            name="tool",
            field=models.CharField(
                choices=[
                    ("domain_security", "Domain Security"),
                    ("subfinder", "Subfinder"),
                    ("dnsx", "DNSx (Resolve)"),
                    ("naabu", "Naabu (Port Scan)"),
                    ("httpx", "HTTPx (Web Probe)"),
                    ("nmap", "Nmap (NSE Vuln Scan)"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstepresult",
            name="tool",
            field=models.CharField(
                choices=[
                    ("domain_security", "Domain Security"),
                    ("subfinder", "Subfinder"),
                    ("dnsx", "DNSx (Resolve)"),
                    ("naabu", "Naabu (Port Scan)"),
                    ("httpx", "HTTPx (Web Probe)"),
                    ("nmap", "Nmap (NSE Vuln Scan)"),
                ],
                max_length=30,
            ),
        ),
    ]
