# Generated by Django 5.2.13 on 2026-04-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0012_add_service_detection_to_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowstep",
            name="tool",
            field=models.CharField(
                choices=[
                    ("domain_security", "Domain Security"),
                    ("subfinder", "Subfinder"),
                    ("dnsx", "DNSx (Resolve)"),
                    ("naabu", "Naabu (Port Scan)"),
                    ("service_detection", "Service Detection"),
                    ("httpx", "HTTPx (Web Probe)"),
                    ("nmap", "Nmap (NSE Vuln Scan)"),
                    ("tls_checker", "TLS Checker"),
                    ("ssh_checker", "SSH Checker"),
                    ("nuclei", "Nuclei (Web Vuln Scan)"),
                    ("web_checker", "Web Checker"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstepresult",
            name="tool",
            field=models.CharField(
                choices=[
                    ("domain_security", "Domain Security"),
                    ("subfinder", "Subfinder"),
                    ("dnsx", "DNSx (Resolve)"),
                    ("naabu", "Naabu (Port Scan)"),
                    ("service_detection", "Service Detection"),
                    ("httpx", "HTTPx (Web Probe)"),
                    ("nmap", "Nmap (NSE Vuln Scan)"),
                    ("tls_checker", "TLS Checker"),
                    ("ssh_checker", "SSH Checker"),
                    ("nuclei", "Nuclei (Web Vuln Scan)"),
                    ("web_checker", "Web Checker"),
                ],
                max_length=30,
            ),
        ),
    ]
