# Generated by Django 5.2.13 on 2026-04-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0018_add_amass_to_infra_scan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("partial", "Partial"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
