# Generated by Django 5.2.13 on 2026-04-10 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scans", "0006_add_triggered_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                ("issuer", models.CharField(blank=True, max_length=500)),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("source", models.CharField(max_length=50)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_certificates",
                        to="scans.scansession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IPAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.GenericIPAddressField()),
                ("version", models.IntegerField()),
                ("source", models.CharField(max_length=50)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_ips",
                        to="scans.scansession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.IntegerField()),
                ("protocol", models.CharField(max_length=10)),
                ("state", models.CharField(max_length=20)),
                ("service", models.CharField(blank=True, max_length=100)),
                ("version", models.CharField(blank=True, max_length=200)),
                ("source", models.CharField(max_length=50)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_ports",
                        to="scans.scansession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("version", models.CharField(blank=True, max_length=100)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("source", models.CharField(max_length=50)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_technologies",
                        to="scans.scansession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=2048)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("source", models.CharField(max_length=50)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_urls",
                        to="scans.scansession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subdomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                ("subdomain", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=50)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_subdomains",
                        to="scans.scansession",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["domain"], name="assets_subd_domain_15f107_idx"
                    ),
                    models.Index(
                        fields=["subdomain"], name="assets_subd_subdoma_289c16_idx"
                    ),
                ],
            },
        ),
    ]
