# Generated by Django 5.2.13 on 2026-04-10 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_alter_subdomain_options_alter_subdomain_session_and_more"),
        ("scans", "0006_add_triggered_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipaddress",
            name="subdomain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ips",
                to="assets.subdomain",
            ),
        ),
        migrations.AddField(
            model_name="subdomain",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subdomain",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="ipaddress",
            index=models.Index(
                fields=["address"], name="assets_ipad_address_a7b33e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subdomain",
            index=models.Index(
                fields=["is_active"], name="assets_subd_is_acti_d4a262_idx"
            ),
        ),
    ]
