# Generated by Django 5.2.13 on 2026-04-10 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_ipaddress_subdomain_subdomain_is_active_and_more"),
        ("scans", "0006_add_triggered_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="port",
            options={"ordering": ["address", "port"]},
        ),
        migrations.AddField(
            model_name="port",
            name="address",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="port",
            name="ip_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ports",
                to="assets.ipaddress",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="protocol",
            field=models.CharField(default="tcp", max_length=10),
        ),
        migrations.AlterField(
            model_name="port",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ports",
                to="scans.scansession",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="state",
            field=models.CharField(default="open", max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="port",
            unique_together={("session", "address", "port", "protocol")},
        ),
        migrations.AddIndex(
            model_name="port",
            index=models.Index(
                fields=["address"], name="assets_port_address_856de6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="port",
            index=models.Index(fields=["port"], name="assets_port_port_6ebee0_idx"),
        ),
    ]
