# Generated by Django 5.2.13 on 2026-04-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_remove_technology_session_delete_certificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="port",
            name="is_web",
            field=models.BooleanField(default=False),
        ),
    ]
