# Generated by Django 5.2.17 on 2026-09-13 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("asset_inventory", "0002_backfill_inventory"),
        ("domains", "0005_domainauthorization"),
        ("findings", "0010_delete_issue"),
    ]

    # State-only: adopt the existing findings_issue table (created by
    # findings/0009_issue) into the issues app — no CREATE, no data migration.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=1024)),
                ("source", models.CharField(db_index=True, max_length=50)),
                (
                    "check_type",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("title", models.CharField(max_length=500)),
                ("target", models.CharField(blank=True, max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="asset_inventory.asset",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="domains.domain",
                    ),
                ),
                (
                    "last_finding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="findings.finding",
                    ),
                ),
            ],
            options={
                "db_table": "findings_issue",
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["domain", "status", "severity"],
                        name="findings_is_domain__687b24_idx",
                    ),
                    models.Index(
                        fields=["status", "severity"],
                        name="findings_is_status_16f986_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("domain", "key"), name="uniq_issue_per_domain"
                    )
                ],
            },
                ),
            ],
        ),
    ]
