# Generated by Django 5.2.17 on 2026-09-14 10:02
#
# Item 2 (identity/register): the Issue key changes from (source, check_type,
# title, target) to (check_id, target). Existing rows are keyed on the old,
# title-based scheme and can't be re-keyed reliably (the coarse tools embedded the
# title in the key, which is exactly what we're removing). Per the decided
# "fresh register" approach, drop all existing Issue rows here — the register
# repopulates with stable check_id-based keys on the next full-scan finalize.
# Triage history from the old scheme is intentionally not carried over.

from django.db import migrations, models


def _clear_issues(apps, schema_editor):
    apps.get_model("issues", "Issue").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="check_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.RunPython(_clear_issues, migrations.RunPython.noop),
    ]
