# Generated by Django 5.2.17 on 2026-09-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_issue_check_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
