# Generated by Django 5.2.17 on 2026-09-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_issue_resolved_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("acknowledged", "Acknowledged"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("false_positive", "False Positive"),
                    ("accepted", "Accepted Risk"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
    ]
