# Generated by Django 5.2.17 on 2026-09-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0005_issue_triage_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="verification_status",
            field=models.CharField(db_index=True, default="unverified", max_length=20),
        ),
    ]
