# Generated by Django 5.2.14 on 2026-05-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0003_remove_domain_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="monitoring_interval_hours",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
