# Generated by Django 5.2.14 on 2026-06-02 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0004_monitoring_interval"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("owner", "Domain Owner"),
                            ("written_consent", "Written Consent"),
                            ("bug_bounty", "Bug Bounty Program"),
                        ],
                        max_length=32,
                    ),
                ),
                ("authorized_at", models.DateField()),
                ("authorized_by", models.CharField(max_length=255)),
                ("auth_reference", models.CharField(blank=True, max_length=500)),
                (
                    "domain",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorization",
                        to="domains.domain",
                    ),
                ),
            ],
        ),
    ]
