# Generated by Django 5.2.13 on 2026-04-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
