# Generated by Django 5.2.17 on 2026-09-04 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("findings", "0007_alter_finding_source"),
        ("scans", "0011_scansession_endpoints_blocked_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("consent_given_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consent_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("consent_version", models.PositiveSmallIntegerField(default=0)),
                (
                    "model_override",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("triage_enabled", models.BooleanField(default=True)),
                ("orchestration_enabled", models.BooleanField(default=True)),
                ("summaries_enabled", models.BooleanField(default=True)),
                ("max_agent_iterations", models.PositiveSmallIntegerField(default=3)),
                ("max_subscans_per_scan", models.PositiveSmallIntegerField(default=2)),
                (
                    "max_findings_per_prompt",
                    models.PositiveSmallIntegerField(default=50),
                ),
            ],
            options={
                "verbose_name": "AI settings",
            },
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("denied", "Denied"),
                            ("limit_reached", "Limit reached"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("iterations_used", models.PositiveSmallIntegerField(default=0)),
                ("subscans_launched", models.PositiveSmallIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("final_summary", models.TextField(blank=True, default="")),
                (
                    "root_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_run",
                        to="scans.scansession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent run",
            },
        ),
        migrations.CreateModel(
            name="AgentAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iteration", models.PositiveSmallIntegerField()),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("run_subscan", "Run subscan"),
                            ("flag_finding", "Flag finding"),
                            ("done", "Done"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("rationale", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("executed", "Executed"),
                            ("denied", "Denied"),
                            ("failed", "Failed"),
                            ("noop", "No-op"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "denial_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscan_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggering_agent_actions",
                        to="scans.scansession",
                    ),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="ai.agentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["iteration", "id"],
            },
        ),
        migrations.CreateModel(
            name="AIInvocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session_uuid",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("triage", "Triage"),
                            ("orchestration", "Orchestration"),
                            ("report_summary", "Report summary"),
                            ("alert_summary", "Alert summary"),
                            ("test", "Connection test"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "backend",
                    models.CharField(default="cloudflare_workers_ai", max_length=40),
                ),
                ("model", models.CharField(max_length=100)),
                ("prompt_tokens", models.IntegerField(blank=True, null=True)),
                ("completion_tokens", models.IntegerField(blank=True, null=True)),
                ("total_tokens", models.IntegerField(blank=True, null=True)),
                ("finding_ids", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("timeout", "Timeout"),
                            ("http_error", "HTTP error"),
                            ("rate_limited", "Rate limited"),
                            ("bad_json", "Bad JSON"),
                            ("schema_mismatch", "Schema mismatch"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_invocations",
                        to="scans.scansession",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI invocation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AITriage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("failed", "Failed")],
                        max_length=20,
                    ),
                ),
                ("overview", models.TextField(blank=True, default="")),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_triage",
                        to="scans.scansession",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI triage",
            },
        ),
        migrations.CreateModel(
            name="AITriageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "finding_key",
                    models.CharField(blank=True, default="", max_length=600),
                ),
                ("rank", models.PositiveIntegerField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("fix_now", "Fix now"),
                            ("plan", "Plan"),
                            ("monitor", "Monitor"),
                            ("likely_noise", "Likely noise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField(blank=True, default="")),
                (
                    "finding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_triage_items",
                        to="findings.finding",
                    ),
                ),
                (
                    "triage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ai.aitriage",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="AISummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("report", "Report"), ("alert", "Alert")],
                        max_length=10,
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_summaries",
                        to="scans.scansession",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI summary",
                "unique_together": {("session", "kind")},
            },
        ),
    ]
