# Generated by Django 5.2.17 on 2026-09-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_alter_aitriage_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisettings",
            name="cloudflare_account_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="cloudflare_api_token",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
