# Generated by Django 5.2.17 on 2026-09-06 03:39

import apps.core.fields
from django.db import migrations

# Secret fields now encrypted at rest — re-save existing rows so any plaintext
# value already stored gets encrypted (runs after the column widens to TEXT).
_SECRET_FIELDS = ["cloudflare_api_token"]


def encrypt_existing(apps, schema_editor):
    Model = apps.get_model("ai", "AISettings")
    for obj in Model.objects.all():
        obj.save(update_fields=_SECRET_FIELDS)


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_aisettings_cloudflare_account_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aisettings",
            name="cloudflare_api_token",
            field=apps.core.fields.EncryptedCharField(
                blank=True, default="", max_length=128
            ),
        ),
        migrations.RunPython(encrypt_existing, migrations.RunPython.noop),
    ]
