# Generated by Django 5.2.13 on 2026-04-09 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0001_initial"),
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scansession",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="workflow.workflow",
            ),
        ),
    ]
