# Generated by Django 5.2.13 on 2026-04-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0005_drop_removed_app_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="scansession",
            name="triggered_by",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("scheduled", "Scheduled"),
                    ("recurring", "Recurring"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
