# Generated by Django 5.2.13 on 2026-04-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0007_alter_scansession_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scandelta",
            name="change_category",
            field=models.CharField(
                choices=[("finding", "Finding"), ("domain_finding", "Domain Finding")],
                max_length=20,
            ),
        ),
    ]
