# Generated by Django 5.2.14 on 2026-05-21 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0008_fix_delta_category_and_workflowrun_cancelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="scansession",
            name="parent_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscans",
                to="scans.scansession",
            ),
        ),
        migrations.AddField(
            model_name="scansession",
            name="subscan_tools",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scansession",
            name="triggered_by",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("scheduled", "Scheduled"),
                    ("recurring", "Recurring"),
                    ("monitoring", "Monitoring"),
                    ("subscan", "Subscan"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
