# Generated by Django 5.2.17 on 2026-09-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0011_scansession_endpoints_blocked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scansession",
            name="triggered_by",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("scheduled", "Scheduled"),
                    ("recurring", "Recurring"),
                    ("monitoring", "Monitoring"),
                    ("subscan", "Subscan"),
                    ("agent", "Agent"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
