# Generated by Django 5.2.17 on 2026-09-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0012_alter_scansession_triggered_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=255, unique=True)),
                ("domain", models.CharField(db_index=True, max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[("once", "One-time"), ("recurring", "Recurring")],
                        max_length=20,
                    ),
                ),
                ("cron", models.CharField(blank=True, default="", max_length=100)),
                ("frequency", models.CharField(blank=True, default="", max_length=50)),
                ("next_run", models.DateTimeField(db_index=True)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["kind", "next_run"],
            },
        ),
    ]
