# Generated by Django 5.2.17 on 2026-09-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0014_scansession_uniq_active_scan_per_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="scansession",
            name="last_progress_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
