# Generated by Django 5.2.17 on 2026-09-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0015_scansession_last_progress_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("cron", models.CharField(blank=True, default="", max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
