# Generated by Django 5.2.13 on 2026-04-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subdomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subdomain", models.CharField(db_index=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subdomains",
                        to="scans.scansession",
                    ),
                ),
            ],
            options={
                "ordering": ["subdomain"],
                "unique_together": {("session", "subdomain")},
            },
        ),
    ]
