# Generated by Django 5.2.13 on 2026-04-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subfinder", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subdomain",
        ),
    ]
