# Generated by Django 5.2.13 on 2026-04-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subfinder", "0002_delete_subdomain"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubfinderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chaos_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ProjectDiscovery Chaos API key.",
                        max_length=200,
                        verbose_name="Chaos Key",
                    ),
                ),
                (
                    "shodan_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Shodan API key.",
                        max_length=200,
                        verbose_name="Shodan Key",
                    ),
                ),
                (
                    "censys_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Censys API ID.",
                        max_length=200,
                        verbose_name="Censys API ID",
                    ),
                ),
                (
                    "censys_secret",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Censys API Secret.",
                        max_length=200,
                        verbose_name="Censys API Secret",
                    ),
                ),
                (
                    "securitytrails_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SecurityTrails API key.",
                        max_length=200,
                        verbose_name="SecurityTrails Key",
                    ),
                ),
                (
                    "virustotal_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="VirusTotal API key.",
                        max_length=200,
                        verbose_name="VirusTotal Key",
                    ),
                ),
                (
                    "github_token",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="GitHub personal access token (improves cert transparency results).",
                        max_length=200,
                        verbose_name="GitHub Token",
                    ),
                ),
                (
                    "bevigil_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="BeVigil API key.",
                        max_length=200,
                        verbose_name="BeVigil Key",
                    ),
                ),
                (
                    "binaryedge_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="BinaryEdge API key.",
                        max_length=200,
                        verbose_name="BinaryEdge Key",
                    ),
                ),
                (
                    "fullhunt_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="FullHunt API key.",
                        max_length=200,
                        verbose_name="FullHunt Key",
                    ),
                ),
                (
                    "hunter_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hunter.io API key.",
                        max_length=200,
                        verbose_name="Hunter Key",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subfinder Configuration",
                "verbose_name_plural": "Subfinder Configuration",
            },
        ),
    ]
