# Generated by Django 5.2.17 on 2026-09-06 03:39

import apps.core.fields
from django.db import migrations

# API keys now encrypted at rest — re-save existing rows to encrypt any
# plaintext already stored (runs after the columns are altered to TEXT).
_SECRET_FIELDS = [
    "chaos_key", "shodan_key", "censys_secret", "securitytrails_key",
    "virustotal_key", "github_token", "bevigil_key", "binaryedge_key",
    "fullhunt_key", "hunter_key",
]


def encrypt_existing(apps, schema_editor):
    Model = apps.get_model("subfinder", "SubfinderConfig")
    for obj in Model.objects.all():
        obj.save(update_fields=_SECRET_FIELDS)


class Migration(migrations.Migration):

    dependencies = [
        ("subfinder", "0003_create_subfinderconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subfinderconfig",
            name="bevigil_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="BeVigil API key.",
                max_length=200,
                verbose_name="BeVigil Key",
            ),
        ),
        migrations.AlterField(
            model_name="subfinderconfig",
            name="binaryedge_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="BinaryEdge API key.",
                max_length=200,
                verbose_name="BinaryEdge Key",
            ),
        ),
        migrations.AlterField(
            model_name="subfinderconfig",
            name="censys_secret",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="Censys API Secret.",
                max_length=200,
                verbose_name="Censys API Secret",
            ),
        ),
        migrations.AlterField(
            model_name="subfinderconfig",
            name="chaos_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="ProjectDiscovery Chaos API key.",
                max_length=200,
                verbose_name="Chaos Key",
            ),
        ),
        migrations.AlterField(
            model_name="subfinderconfig",
            name="fullhunt_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="FullHunt API key.",
                max_length=200,
                verbose_name="FullHunt Key",
            ),
        ),
        migrations.AlterField(
            model_name="subfinderconfig",
            name="github_token",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="GitHub personal access token (improves cert transparency results).",
                max_length=200,
                verbose_name="GitHub Token",
            ),
        ),
        migrations.AlterField(
            model_name="subfinderconfig",
            name="hunter_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="Hunter.io API key.",
                max_length=200,
                verbose_name="Hunter Key",
            ),
        ),
        migrations.AlterField(
            model_name="subfinderconfig",
            name="securitytrails_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="SecurityTrails API key.",
                max_length=200,
                verbose_name="SecurityTrails Key",
            ),
        ),
        migrations.AlterField(
            model_name="subfinderconfig",
            name="shodan_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="Shodan API key.",
                max_length=200,
                verbose_name="Shodan Key",
            ),
        ),
        migrations.AlterField(
            model_name="subfinderconfig",
            name="virustotal_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="VirusTotal API key.",
                max_length=200,
                verbose_name="VirusTotal Key",
            ),
        ),
        migrations.RunPython(encrypt_existing, migrations.RunPython.noop),
    ]
