# Generated by Django 5.2.13 on 2026-04-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0002_domain_is_primary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="notes",
        ),
    ]
