# Generated by Django 5.2.13 on 2026-04-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scans", "0003_add_uuid_to_scansession"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(db_index=True, max_length=255)),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("dns", "DNS"),
                            ("ssl", "SSL/TLS"),
                            ("email", "Email Security"),
                            ("rdap", "RDAP/Domain"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("remediation", models.TextField(blank=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_findings",
                        to="scans.scansession",
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "-discovered_at"],
            },
        ),
    ]
