# Generated by Django 5.2.13 on 2026-04-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain_security", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainfinding",
            name="check_type",
            field=models.CharField(
                choices=[
                    ("dns", "DNS"),
                    ("email", "Email Security"),
                    ("rdap", "RDAP/Domain"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
