# Generated by Django 5.2.13 on 2026-04-11 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain_security", "0002_remove_ssl_check_type"),
        ("findings", "0002_migrate_existing_findings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DomainFinding",
        ),
    ]
