apiVersion: v1
kind: ConfigMap
metadata:
  name: openeasd-config
  namespace: openeasd
data:
  ALLOWED_HOSTS: "openeasd.cybersecify.com,openeasd.local,localhost"
  CSRF_TRUSTED_ORIGINS: "https://openeasd.cybersecify.com,http://openeasd.local"
  DEBUG: "False"
  DB_NAME: "data/openeasd.db"
  ALERT_SEVERITY_THRESHOLD: "high"
  SCAN_DAILY_HOUR: "2"
  SCAN_DAILY_MINUTE: "0"
