# Generated by Django 5.2.13 on 2026-04-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NucleiFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(db_index=True, max_length=255)),
                ("port", models.IntegerField(blank=True, null=True)),
                ("template_id", models.CharField(max_length=200)),
                ("template_name", models.CharField(blank=True, max_length=500)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("matched_at", models.CharField(blank=True, max_length=500)),
                ("cvss_score", models.FloatField(blank=True, null=True)),
                ("cve_id", models.CharField(blank=True, max_length=50)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("is_new", models.BooleanField(default=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuclei_findings",
                        to="scans.scansession",
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "-discovered_at"],
            },
        ),
    ]
