# Generated by Django 5.2.13 on 2026-04-12 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nuclei", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NucleiFinding",
        ),
    ]
