# Generated by Django 5.2.13 on 2026-04-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScanConfiguration",
        ),
    ]
