# Generated by Django 5.2.17 on 2026-09-09 06:03

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToolCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shodan_api_key",
                    apps.core.fields.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "hibp_api_key",
                    apps.core.fields.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "github_token",
                    apps.core.fields.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "github_secret",
                    apps.core.fields.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "dns_history_api_url",
                    apps.core.fields.EncryptedTextField(blank=True, default=""),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tool credentials",
            },
        ),
    ]
