# Generated by Django 5.2.13 on 2026-04-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField()),
                ("protocol", models.CharField(default="tcp", max_length=10)),
                ("state", models.CharField(default="open", max_length=20)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="port_results",
                        to="scans.scansession",
                    ),
                ),
            ],
            options={
                "ordering": ["host", "port"],
                "unique_together": {("session", "host", "port", "protocol")},
            },
        ),
    ]
