# Generated by Django 5.2.13 on 2026-04-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("naabu", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PortResult",
        ),
    ]
