# Generated by Django 5.2.13 on 2026-04-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("naabu", "0002_delete_portresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="NaabuConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "top_ports",
                    models.CharField(
                        choices=[
                            ("100", "Top 100"),
                            ("1000", "Top 1000"),
                            ("full", "All 65535"),
                            ("custom", "Custom (see Custom Ports field)"),
                        ],
                        default="100",
                        help_text="Number of top ports to scan. Ignored when Custom Ports is set.",
                        max_length=10,
                    ),
                ),
                (
                    "custom_ports",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom port list/range, e.g. 22,80,443,8080-8090. Overrides Top Ports when set.",
                        max_length=500,
                    ),
                ),
                (
                    "rate",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Packets per second. Lower values are stealthier but slower.",
                    ),
                ),
                (
                    "scan_timeout",
                    models.PositiveIntegerField(
                        default=900,
                        help_text="Maximum scan duration in seconds before naabu is killed.",
                    ),
                ),
                (
                    "exclude_ports",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ports to exclude, e.g. 9200,27017. Leave blank to exclude nothing.",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "verbose_name": "Naabu Configuration",
                "verbose_name_plural": "Naabu Configuration",
            },
        ),
    ]
