# Generated by Django 5.2.13 on 2026-04-10 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        ("scans", "0006_add_triggered_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subdomain",
            options={"ordering": ["subdomain"]},
        ),
        migrations.AlterField(
            model_name="subdomain",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subdomains",
                to="scans.scansession",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subdomain",
            unique_together={("session", "subdomain")},
        ),
    ]
