# Generated by Django 5.2.13 on 2026-04-10 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_alter_port_options_port_address_port_ip_address_and_more"),
        ("scans", "0006_add_triggered_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="url",
            options={"ordering": ["url"]},
        ),
        migrations.AddField(
            model_name="url",
            name="content_length",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="url",
            name="host",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="url",
            name="port",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="urls",
                to="assets.port",
            ),
        ),
        migrations.AddField(
            model_name="url",
            name="port_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="url",
            name="scheme",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="url",
            name="subdomain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="urls",
                to="assets.subdomain",
            ),
        ),
        migrations.AddField(
            model_name="url",
            name="web_server",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="url",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="urls",
                to="scans.scansession",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="url",
            unique_together={("session", "url")},
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["host"], name="assets_url_host_df7654_idx"),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(
                fields=["status_code"], name="assets_url_status__a21c44_idx"
            ),
        ),
    ]
