# Generated by Django 5.2.13 on 2026-04-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_alter_url_options_url_content_length_url_host_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technology",
            name="session",
        ),
        migrations.DeleteModel(
            name="Certificate",
        ),
        migrations.DeleteModel(
            name="Technology",
        ),
    ]
