"""typosquat analyzer — turns registered-lookalike records into shared Findings.

One Finding per registered lookalike domain (``check_type="lookalike_domain"``):

  * ``medium`` when the lookalike has A or MX records — it can already host a
    phishing page or receive mail, i.e. it is weaponizable against the org's
    brand / users.
  * ``low`` when it is only registered / parked (NS but no A/MX) — no live
    phishing surface yet, but worth monitoring: someone owns a name built to be
    confused with the org's.

This is threat-surface intel: the finding names the lookalike, the records it
carries, and the technique that produced it, so a defender can prioritise
monitoring, defensive registration, or a takedown request.
"""

import logging

from apps.core.findings.models import Finding

logger = logging.getLogger(__name__)


def _record_summary(record: dict) -> str:
    parts = []
    if record.get("has_a"):
        ips = ", ".join(record.get("resolved_ips") or []) or "yes"
        parts.append(f"A ({ips})")
    if record.get("has_mx"):
        parts.append("MX (can receive mail)")
    if record.get("has_ns") and not (record.get("has_a") or record.get("has_mx")):
        parts.append("NS only (registered / parked)")
    return ", ".join(parts) or "registered"


def analyze(session, results) -> list[Finding]:
    findings: list[Finding] = []
    apex = getattr(session, "domain", "") or ""

    for record in results or []:
        if not isinstance(record, dict):
            continue
        candidate = record.get("candidate")
        if not candidate:
            continue

        weaponizable = bool(record.get("has_a") or record.get("has_mx"))
        severity = "medium" if weaponizable else "low"
        summary = _record_summary(record)

        findings.append(Finding(
            session=session,
            source="typosquat",
            check_type="lookalike_domain",
            severity=severity,
            target=candidate,
            title=f"Registered lookalike domain {candidate} (targets {apex})",
            description=(
                f"{candidate} is a registered lookalike of {apex}, generated by the "
                f"'{record.get('technique', 'typo')}' typosquatting technique. DNS "
                f"records seen: {summary}. "
                + (
                    "Because it resolves and/or accepts mail, it can be used right "
                    "now to host a phishing page impersonating the brand or to send "
                    "spoofed email to staff, customers, or partners."
                    if weaponizable else
                    "It is registered but not yet serving content or mail — a "
                    "latent phishing / brand-abuse asset worth monitoring in case "
                    "it is weaponized later."
                )
            ),
            remediation=(
                "Confirm the domain is not one you own. Monitor it for changes "
                "(new A/MX/TLS records), consider defensively registering the most "
                "convincing lookalikes, and report clear phishing infrastructure to "
                "the registrar / hosting provider for takedown."
            ),
            extra={
                "candidate": candidate,
                "technique": record.get("technique"),
                "has_a": bool(record.get("has_a")),
                "has_mx": bool(record.get("has_mx")),
                "has_ns": bool(record.get("has_ns")),
                "resolved_ips": record.get("resolved_ips") or [],
                "targets": apex,
                "source_data": "typosquat",
            },
        ))

    return findings
