"""typosquat analyzer — turns registered-lookalike records into shared Findings.

One Finding per registered lookalike domain (``check_type="lookalike_domain"``):

  * ``high`` when the live homepage carries a login form — confirmed credential
    phishing, takedown-worthy. (Brand mentions alone never reach high: short
    brand strings collide with unrelated organizations' legitimate names.)
  * ``medium`` when the lookalike has A or MX records and is not parked — it
    can host a phishing page or receive mail, i.e. it is weaponizable against
    the org's brand / users.
  * ``low`` when it is only registered (NS but no A/MX) or sits at a known
    domain-parking / for-sale service — speculation, not live phishing
    surface; worth monitoring.

This is threat-surface intel: the finding names the lookalike, the records it
carries, and the technique that produced it, so a defender can prioritise
monitoring, defensive registration, or a takedown request.
"""

import logging

from apps.core.data.findings.models import Finding

logger = logging.getLogger(__name__)


def _record_summary(record: dict) -> str:
    parts = []
    if record.get("has_a"):
        ips = ", ".join(record.get("resolved_ips") or []) or "yes"
        parts.append(f"A ({ips})")
    if record.get("has_mx"):
        parts.append("MX (can receive mail)")
    if record.get("has_ns") and not (record.get("has_a") or record.get("has_mx")):
        parts.append("NS only (registered / parked)")
    return ", ".join(parts) or "registered"


def analyze(session, results) -> list[Finding]:
    findings: list[Finding] = []
    apex = getattr(session, "domain", "") or ""

    for record in results or []:
        if not isinstance(record, dict):
            continue
        candidate = record.get("candidate")
        if not candidate:
            continue

        weaponizable = bool(record.get("has_a") or record.get("has_mx"))
        login_form = bool(record.get("login_form"))
        brand_mentioned = bool(record.get("brand_mentioned"))
        parked = bool(record.get("parked"))
        # Weaponized = a login form on the live homepage (credential phishing) —
        # a confirmed threat worth a takedown. Brand mentions alone are NOT
        # enough for high: short brand strings legitimately appear in unrelated
        # organizations' own names (a lookalike scan for "amnic" flagged the
        # Armenia Network Information Centre as "active impersonation" because
        # its page says AMNIC — its own name). Mentions stay a medium-level
        # review signal in the description.
        weaponized = login_form
        if weaponized:
            severity = "high"
        elif parked:
            # Parked at a domain-parking / for-sale service: speculation, not
            # phishing infrastructure. The registrar-default A/MX records don't
            # make it weaponizable by whoever bought the name.
            severity = "low"
        elif weaponizable:
            severity = "medium"
        else:
            severity = "low"
        summary = _record_summary(record)

        if weaponized:
            weapon_line = (
                "Its live homepage shows a login form (credential phishing)"
                + (" and mentions your brand" if brand_mentioned else "")
                + " — this is an active impersonation of your brand, not just a "
                "registered name. Prioritise a takedown."
            )
        elif parked:
            weapon_line = (
                "It sits at a domain-parking / for-sale service — registered "
                "speculation, not live phishing infrastructure. Monitor for a "
                "change of hosting, and consider buying it if the name is "
                "convincing."
            )
        elif weaponizable:
            weapon_line = (
                "Because it resolves and/or accepts mail, it can be used right "
                "now to host a phishing page impersonating the brand or to send "
                "spoofed email to staff, customers, or partners."
                + (
                    " Its homepage mentions your brand — review it manually "
                    "(this can also be an unrelated organization with a "
                    "similar name)."
                    if brand_mentioned else ""
                )
            )
        else:
            weapon_line = (
                "It is registered but not yet serving content or mail — a "
                "latent phishing / brand-abuse asset worth monitoring in case "
                "it is weaponized later."
            )

        findings.append(Finding(
            session=session,
            source="typosquat",
            check_type="lookalike_domain",
            severity=severity,
            target=candidate,
            title=f"Registered lookalike domain {candidate} (targets {apex})",
            description=(
                f"{candidate} is a registered lookalike of {apex}, generated by the "
                f"'{record.get('technique', 'typo')}' typosquatting technique. DNS "
                f"records seen: {summary}. " + weapon_line
            ),
            remediation=(
                "Confirm the domain is not one you own. Monitor it for changes "
                "(new A/MX/TLS records), consider defensively registering the most "
                "convincing lookalikes, and report clear phishing infrastructure to "
                "the registrar / hosting provider for takedown."
            ),
            extra={
                "candidate": candidate,
                "technique": record.get("technique"),
                "has_a": bool(record.get("has_a")),
                "has_mx": bool(record.get("has_mx")),
                "has_ns": bool(record.get("has_ns")),
                "resolved_ips": record.get("resolved_ips") or [],
                "login_form": login_form,
                "parked": parked,
                "brand_mentioned": brand_mentioned,
                "brand_mention_count": record.get("brand_mention_count", 0),
                "content_checked": bool(record.get("content_checked")),
                "targets": apex,
                "source_data": "typosquat",
            },
        ))

    return findings
