# Generated by Django 5.2.17 on 2026-09-06 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("domains", "0005_domainauthorization"),
        ("scans", "0014_scansession_uniq_active_scan_per_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("subdomain", "Subdomain"),
                            ("ip", "IP Address"),
                            ("port", "Port"),
                            ("url", "URL"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(max_length=2048)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("gone", "Gone")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="domains.domain",
                    ),
                ),
                (
                    "last_scan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="scans.scansession",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "key"],
                "indexes": [
                    models.Index(
                        fields=["domain", "kind", "status"],
                        name="asset_inven_domain__e99590_idx",
                    ),
                    models.Index(
                        fields=["kind", "status"], name="asset_inven_kind_21f99f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("domain", "kind", "key"), name="uniq_asset_per_domain"
                    )
                ],
            },
        ),
    ]
