# Generated by Django 5.2.13 on 2026-04-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowstep",
            name="tool",
            field=models.CharField(
                choices=[
                    ("domain_security", "Domain Security"),
                    ("ssl_checker", "SSL Checker"),
                    ("subfinder", "Subfinder"),
                    ("naabu", "Naabu (Port Scan)"),
                    ("nmap", "Nmap (Service Scan)"),
                    ("nuclei", "Nuclei (Vuln Scan)"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstepresult",
            name="tool",
            field=models.CharField(
                choices=[
                    ("domain_security", "Domain Security"),
                    ("ssl_checker", "SSL Checker"),
                    ("subfinder", "Subfinder"),
                    ("naabu", "Naabu (Port Scan)"),
                    ("nmap", "Nmap (Service Scan)"),
                    ("nuclei", "Nuclei (Vuln Scan)"),
                ],
                max_length=30,
            ),
        ),
    ]
