# Generated by Django 5.2.13 on 2026-04-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0002_remove_dns_analyzer_email_security"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowstep",
            name="tool",
            field=models.CharField(
                choices=[
                    ("domain_security", "Domain Security"),
                    ("subfinder", "Subfinder"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstepresult",
            name="tool",
            field=models.CharField(
                choices=[
                    ("domain_security", "Domain Security"),
                    ("subfinder", "Subfinder"),
                ],
                max_length=30,
            ),
        ),
    ]
