# Generated by Django 5.2.13 on 2026-04-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0013_alter_workflowstep_tool_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowstep",
            name="tool",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="workflowstepresult",
            name="tool",
            field=models.CharField(max_length=50),
        ),
    ]
