# Generated by Django 5.2.13 on 2026-04-11 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0005_alter_url_options_url_content_length_url_host_and_more"),
        ("scans", "0006_add_triggered_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("domain_security", "Domain Security"),
                            ("nmap", "Nmap NSE"),
                            ("nuclei", "Nuclei"),
                            ("ssl_checker", "SSL Checker"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "check_type",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("remediation", models.TextField(blank=True)),
                ("target", models.CharField(blank=True, db_index=True, max_length=255)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ip_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="assets.ipaddress",
                    ),
                ),
                (
                    "port",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="assets.port",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="scans.scansession",
                    ),
                ),
                (
                    "subdomain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="assets.subdomain",
                    ),
                ),
                (
                    "url",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="assets.url",
                    ),
                ),
            ],
            options={
                "ordering": ["-discovered_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "severity"],
                        name="findings_fi_session_5d6209_idx",
                    ),
                    models.Index(
                        fields=["source", "severity"],
                        name="findings_fi_source_28c38d_idx",
                    ),
                ],
            },
        ),
    ]
