# Generated by Django 5.2.13 on 2026-04-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0003_finding_lifecycle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="source",
            field=models.CharField(
                choices=[
                    ("domain_security", "Domain Security"),
                    ("nmap", "Nmap NSE"),
                    ("tls_checker", "TLS Checker"),
                    ("ssh_checker", "SSH Checker"),
                    ("nuclei", "Nuclei"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
