# Generated by Django 5.2.13 on 2026-04-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0006_alter_finding_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="source",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
