# Generated by Django 5.2.17 on 2026-09-06 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_inventory", "0001_initial"),
        ("findings", "0007_alter_finding_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings",
                to="asset_inventory.asset",
            ),
        ),
    ]
