# Generated by Django 5.2.13 on 2026-04-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AmassConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to disable amass entirely without removing it from workflows.",
                    ),
                ),
                (
                    "passive_only",
                    models.BooleanField(
                        default=False,
                        help_text="When checked, amass runs passive enumeration only (no DNS brute force, no zone transfer attempts). Faster but less thorough.",
                        verbose_name="Passive only",
                    ),
                ),
                (
                    "wordlist_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Absolute path to a DNS wordlist for brute-force subdomain discovery (e.g. /opt/wordlists/subdomains-top1million.txt). Leave blank to skip brute force.",
                        max_length=500,
                        verbose_name="Wordlist path",
                    ),
                ),
                (
                    "scan_timeout",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Maximum scan duration in minutes before amass is killed. Default: 30.",
                        verbose_name="Timeout (minutes)",
                    ),
                ),
                (
                    "chaos_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ProjectDiscovery Chaos API key.",
                        max_length=200,
                        verbose_name="Chaos Key",
                    ),
                ),
                (
                    "shodan_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Shodan API key.",
                        max_length=200,
                        verbose_name="Shodan Key",
                    ),
                ),
                (
                    "censys_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Censys API ID.",
                        max_length=200,
                        verbose_name="Censys API ID",
                    ),
                ),
                (
                    "censys_secret",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Censys API Secret.",
                        max_length=200,
                        verbose_name="Censys API Secret",
                    ),
                ),
                (
                    "securitytrails_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SecurityTrails API key.",
                        max_length=200,
                        verbose_name="SecurityTrails Key",
                    ),
                ),
                (
                    "virustotal_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="VirusTotal API key.",
                        max_length=200,
                        verbose_name="VirusTotal Key",
                    ),
                ),
                (
                    "passivetotal_username",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="PassiveTotal (RiskIQ) account username.",
                        max_length=200,
                        verbose_name="PassiveTotal Username",
                    ),
                ),
                (
                    "passivetotal_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="PassiveTotal (RiskIQ) API key.",
                        max_length=200,
                        verbose_name="PassiveTotal Key",
                    ),
                ),
                (
                    "whoisxmlapi_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="WhoisXMLAPI key.",
                        max_length=200,
                        verbose_name="WhoisXMLAPI Key",
                    ),
                ),
                (
                    "github_token",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="GitHub personal access token (improves cert transparency results).",
                        max_length=200,
                        verbose_name="GitHub Token",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amass Configuration",
                "verbose_name_plural": "Amass Configuration",
            },
        ),
    ]
