# Generated by Django 5.2.13 on 2026-04-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("amass", "0001_create_amassconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amassconfig",
            name="passive_only",
        ),
    ]
