# Generated by Django 5.2.13 on 2026-04-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amass", "0002_remove_passive_only"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amassconfig",
            name="wordlist_path",
        ),
        migrations.AddField(
            model_name="amassconfig",
            name="wordlist_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a DNS wordlist for brute-force subdomain discovery (e.g. subdomains-top1million-5000.txt from SecLists). Leave blank to skip brute force.",
                null=True,
                upload_to="wordlists/",
                verbose_name="Wordlist file",
            ),
        ),
    ]
