# Generated by Django 5.2.17 on 2026-09-06 03:39

import apps.core.fields
from django.db import migrations

# API keys now encrypted at rest — re-save existing rows to encrypt any
# plaintext already stored (runs after the columns are altered to TEXT).
_SECRET_FIELDS = [
    "chaos_key", "shodan_key", "censys_secret", "securitytrails_key",
    "virustotal_key", "passivetotal_key", "whoisxmlapi_key", "github_token",
]


def encrypt_existing(apps, schema_editor):
    Model = apps.get_model("amass", "AmassConfig")
    for obj in Model.objects.all():
        obj.save(update_fields=_SECRET_FIELDS)


class Migration(migrations.Migration):

    dependencies = [
        ("amass", "0003_wordlist_file_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amassconfig",
            name="censys_secret",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="Censys API Secret.",
                max_length=200,
                verbose_name="Censys API Secret",
            ),
        ),
        migrations.AlterField(
            model_name="amassconfig",
            name="chaos_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="ProjectDiscovery Chaos API key.",
                max_length=200,
                verbose_name="Chaos Key",
            ),
        ),
        migrations.AlterField(
            model_name="amassconfig",
            name="github_token",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="GitHub personal access token (improves cert transparency results).",
                max_length=200,
                verbose_name="GitHub Token",
            ),
        ),
        migrations.AlterField(
            model_name="amassconfig",
            name="passivetotal_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="PassiveTotal (RiskIQ) API key.",
                max_length=200,
                verbose_name="PassiveTotal Key",
            ),
        ),
        migrations.AlterField(
            model_name="amassconfig",
            name="securitytrails_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="SecurityTrails API key.",
                max_length=200,
                verbose_name="SecurityTrails Key",
            ),
        ),
        migrations.AlterField(
            model_name="amassconfig",
            name="shodan_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="Shodan API key.",
                max_length=200,
                verbose_name="Shodan Key",
            ),
        ),
        migrations.AlterField(
            model_name="amassconfig",
            name="virustotal_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="VirusTotal API key.",
                max_length=200,
                verbose_name="VirusTotal Key",
            ),
        ),
        migrations.AlterField(
            model_name="amassconfig",
            name="whoisxmlapi_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="WhoisXMLAPI key.",
                max_length=200,
                verbose_name="WhoisXMLAPI Key",
            ),
        ),
        migrations.RunPython(encrypt_existing, migrations.RunPython.noop),
    ]
