# Generated by Django 5.2.13 on 2026-04-09 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scans", "0003_add_uuid_to_scansession"),
    ]

    operations = [
        migrations.CreateModel(
            name="FindingTypeSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("check_type", models.CharField(max_length=50)),
                ("severity", models.CharField(max_length=20)),
                ("occurrence_count", models.IntegerField(default=0)),
                ("last_seen", models.DateTimeField()),
            ],
            options={
                "ordering": ["-occurrence_count"],
                "unique_together": {("title", "check_type")},
            },
        ),
        migrations.CreateModel(
            name="ScanSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(db_index=True, max_length=255)),
                ("scan_date", models.DateTimeField(db_index=True)),
                ("critical_count", models.IntegerField(default=0)),
                ("high_count", models.IntegerField(default=0)),
                ("medium_count", models.IntegerField(default=0)),
                ("low_count", models.IntegerField(default=0)),
                ("total_findings", models.IntegerField(default=0)),
                ("new_exposures", models.IntegerField(default=0)),
                ("removed_exposures", models.IntegerField(default=0)),
                ("tool_breakdown", models.JSONField(default=dict)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="scans.scansession",
                    ),
                ),
            ],
            options={
                "ordering": ["-scan_date"],
            },
        ),
    ]
