# Generated by Django 5.2.17 on 2026-09-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scansummary",
            name="exposure_grade",
            field=models.CharField(default="A", max_length=1),
        ),
        migrations.AddField(
            model_name="scansummary",
            name="exposure_score",
            field=models.IntegerField(default=0),
        ),
    ]
