# Generated by Django 5.2.13 on 2026-04-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0002_migrate_existing_findings"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="assigned_to",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="finding",
            name="resolution_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("acknowledged", "Acknowledged"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("false_positive", "False Positive"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
    ]
