# Generated by Django 5.2.13 on 2026-04-12 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0005_alter_finding_source"),
        ("web_assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="findings",
                to="web_assets.url",
            ),
        ),
    ]
