# Generated by Django 5.2.17 on 2026-09-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0009_issue"),
    ]

    # State-only: the Issue model moved to the `issues` app (D-017). Remove it from
    # the findings app's state WITHOUT dropping the table — the `issues` app adopts
    # the same table (findings_issue) in its 0001 migration. No DDL, no data loss.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name="Issue")],
            database_operations=[],
        ),
    ]
