# Generated by Django 5.2.17 on 2026-09-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0010_delete_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="check_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
