# Generated by Django 5.2.17 on 2026-09-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0012_alter_finding_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="verification_status",
            field=models.CharField(db_index=True, default="unverified", max_length=20),
        ),
        migrations.AddField(
            model_name="finding",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
