# Generated by Django 5.2.13 on 2026-04-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField()),
                ("service_name", models.CharField(blank=True, max_length=100)),
                ("version", models.CharField(blank=True, max_length=200)),
                ("protocol", models.CharField(default="tcp", max_length=10)),
                ("state", models.CharField(default="open", max_length=20)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="scans.scansession",
                    ),
                ),
            ],
            options={
                "ordering": ["host", "port"],
                "unique_together": {("session", "host", "port", "protocol")},
            },
        ),
    ]
