# Generated by Django 5.2.13 on 2026-04-10 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_alter_port_options_port_address_port_ip_address_and_more"),
        ("nmap", "0001_initial"),
        ("scans", "0006_add_triggered_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="NmapFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(db_index=True, max_length=64)),
                ("port_number", models.IntegerField()),
                ("service", models.CharField(blank=True, max_length=100)),
                ("version", models.CharField(blank=True, max_length=200)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("nse_script", models.CharField(default="vulners", max_length=100)),
                ("cve", models.CharField(blank=True, db_index=True, max_length=30)),
                ("cvss_score", models.FloatField(blank=True, null=True)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "port",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nmap_findings",
                        to="assets.port",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nmap_findings",
                        to="scans.scansession",
                    ),
                ),
            ],
            options={
                "ordering": ["-cvss_score", "-discovered_at"],
            },
        ),
        migrations.DeleteModel(
            name="ServiceResult",
        ),
        migrations.AddIndex(
            model_name="nmapfinding",
            index=models.Index(
                fields=["address", "port_number"], name="nmap_nmapfi_address_93f295_idx"
            ),
        ),
    ]
