# Generated by Django 5.2.13 on 2026-04-11 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0002_nmapfinding_delete_serviceresult_and_more"),
        ("findings", "0002_migrate_existing_findings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NmapFinding",
        ),
    ]
